### ISSUE TITLE
Acronyms with no vowels causes error

### ISSUE THREAD

**Issue by danuvian** [spilth/piglib#2]
An acronym like PBS and SSN causes an error because the code does not handle a case where the word has no vowel. 

I fixed the issue and created a pull request. Let me know if you have any comments.

**Comment by spilth** [comment]
Hi @danuvian,

You bring up a good point, though I don't know what the rules for initialisms and acronyms are in Pig Latin. And since Acronyms are pronounceable and initialisms are not, they could have different rules.

So I think we'd first need to define how they work, then we can add tests and see if your PR works against them.
